import 'function_call_results.dart';
import 'model_content_parts.dart';
import 'streaming_usage.dart';
import 'user_content_parts.dart';

enum MessageRole { system, user, assistant, tool }

/// Base class for all messages exchanged with an LLM.
abstract class LLMMessage {
  final MessageRole role;
  LLMMessage(this.role);

  Map<String, dynamic> toJson();

  static LLMMessage fromJson(Map<String, dynamic> json) {
    final roleStr = json['role'] as String;
    final role = MessageRole.values.firstWhere(
      (e) => e.toString().split('.').last == roleStr,
    );

    switch (role) {
      case MessageRole.system:
        return SystemMessage.fromJson(json);
      case MessageRole.user:
        return UserMessage.fromJson(json);
      case MessageRole.assistant:
        return ModelMessage.fromJson(json);
      case MessageRole.tool:
        return FunctionExecutionResultMessage.fromJson(json);
    }
  }
}

class SystemMessage extends LLMMessage {
  final String content;
  SystemMessage(this.content) : super(MessageRole.system);

  @override
  Map<String, dynamic> toJson() => {'role': 'system', 'content': content};

  factory SystemMessage.fromJson(Map<String, dynamic> json) {
    return SystemMessage(json['content'] as String);
  }
}

/// A message sent by the user, which can contain multiple content parts
/// (text, image, video, audio, document).
class UserMessage extends LLMMessage {
  final List<UserContentPart> contents;
  final int timestamp;
  final Map<String, dynamic>? metadata;

  UserMessage(this.contents, {int? timestamp, this.metadata})
    : timestamp = timestamp ?? DateTime.now().microsecondsSinceEpoch,
      super(MessageRole.user);

  /// Convenience constructor for single text content
  UserMessage.text(String text, {this.metadata})
    : contents = [TextPart(text)],
      timestamp = DateTime.now().microsecondsSinceEpoch,
      super(MessageRole.user);

  @override
  Map<String, dynamic> toJson() => {
    'role': 'user',
    'timestamp': timestamp,
    'contents': contents.map((e) => e.toJson()).toList(),
    if (metadata != null) 'metadata': metadata,
  };

  factory UserMessage.fromJson(Map<String, dynamic> json) {
    final contents = (json['contents'] as List)
        .map((e) => UserContentPart.fromJson(e as Map<String, dynamic>))
        .toList();
    return UserMessage(
      contents,
      timestamp: json['timestamp'],
      metadata: json['metadata'],
    );
  }
}

/// A message generated by the AI model, including text output,
/// function calls, and multi-modal content.
class ModelMessage extends LLMMessage {
  final String? thought;
  final String? thoughtSignature; // Optional verification signature
  /// Provider-native assistant content blocks.
  ///
  /// Some providers, notably Anthropic Messages, require exact block-level
  /// round-tripping for content such as `thinking`, `redacted_thinking`, and
  /// interleaved `tool_use` blocks. The flattened fields below remain the
  /// provider-neutral view used by agents, while this field preserves the raw
  /// provider order for clients that need it.
  final List<Map<String, dynamic>> contentBlocks;
  final List<FunctionCall> functionCalls;
  final String? textOutput;
  final List<ModelImagePart> imageOutputs;
  final List<ModelVideoPart> videoOutputs;
  final List<ModelAudioPart> audioOutputs;
  final ModelUsage? usage;
  final Map<String, dynamic>? metadata;
  final String? stopReason;
  final String model;
  final String? responseId;
  final int timestamp;

  ModelMessage({
    this.thought,
    this.thoughtSignature,
    this.contentBlocks = const [],
    this.functionCalls = const [],
    this.textOutput,
    this.imageOutputs = const [],
    this.videoOutputs = const [],
    this.audioOutputs = const [],
    this.usage,
    this.metadata,
    this.stopReason,
    required this.model,
    this.responseId,
    int? timestamp,
  }) : timestamp = timestamp ?? DateTime.now().microsecondsSinceEpoch,
       super(MessageRole.assistant);

  @override
  Map<String, dynamic> toJson() => {
    'role': 'assistant',
    if (thought != null) 'thought': thought,
    if (thoughtSignature != null) 'thoughtSignature': thoughtSignature,
    if (contentBlocks.isNotEmpty)
      'contentBlocks': contentBlocks.map((e) => Map.of(e)).toList(),
    if (textOutput != null) 'textOutput': textOutput,
    if (functionCalls.isNotEmpty)
      'functionCalls': functionCalls.map((e) => e.toJson()).toList(),
    if (imageOutputs.isNotEmpty)
      'imageOutputs': imageOutputs.map((e) => e.toJson()).toList(),
    if (videoOutputs.isNotEmpty)
      'videoOutputs': videoOutputs.map((e) => e.toJson()).toList(),
    if (audioOutputs.isNotEmpty)
      'audioOutputs': audioOutputs.map((e) => e.toJson()).toList(),
    if (usage != null) 'usage': usage!.toJson(),
    if (metadata != null) 'metadata': metadata,
    if (stopReason != null) 'stopReason': stopReason,
    'model': model,
    if (responseId != null) 'responseId': responseId,
    'timestamp': timestamp,
  };

  factory ModelMessage.fromJson(Map<String, dynamic> json) {
    return ModelMessage(
      thought: json['thought'] as String?,
      thoughtSignature: json['thoughtSignature'] as String?,
      contentBlocks:
          (json['contentBlocks'] as List?)
              ?.map((e) => Map<String, dynamic>.from(e as Map))
              .toList() ??
          [],
      textOutput: json['textOutput'] as String?,
      functionCalls:
          (json['functionCalls'] as List?)
              ?.map((e) => FunctionCall.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      imageOutputs:
          (json['imageOutputs'] as List?)
              ?.map((e) => ModelImagePart.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      videoOutputs:
          (json['videoOutputs'] as List?)
              ?.map((e) => ModelVideoPart.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      audioOutputs:
          (json['audioOutputs'] as List?)
              ?.map((e) => ModelAudioPart.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      usage: json['usage'] != null
          ? ModelUsage.fromJson(json['usage'] as Map<String, dynamic>)
          : null,
      metadata: json['metadata'] as Map<String, dynamic>?,
      stopReason: json['stopReason'] as String?,
      model: json['model'] as String,
      responseId: json['responseId'] as String?,
      timestamp: json['timestamp'] as int,
    );
  }
}

class FunctionExecutionResultMessage extends LLMMessage {
  final List<FunctionExecutionResult> results;
  final int timestamp;

  FunctionExecutionResultMessage({required this.results, int? timestamp})
    : timestamp = timestamp ?? DateTime.now().microsecondsSinceEpoch,
      super(MessageRole.tool);

  @override
  Map<String, dynamic> toJson() => {
    'role': 'tool',
    'results': results.map((e) => e.toJson()).toList(),
    'timestamp': timestamp,
  };

  factory FunctionExecutionResultMessage.fromJson(Map<String, dynamic> json) {
    return FunctionExecutionResultMessage(
      results: (json['results'] as List)
          .map(
            (e) => FunctionExecutionResult.fromJson(e as Map<String, dynamic>),
          )
          .toList(),
      timestamp: json['timestamp'] as int,
    );
  }
}
